ImportError: No module named parse
mysql-connector-python >= 8.0.24 does not support Python 2.x anymore
https://dev.mysql.com/doc/relnotes/connector-python/en/news-8-0-24.html